sources:
  - name: olist
    database: dataengineeringpractice-464317
    schema: olist
    tables:
    - name: customers
    - name: geolocations
    - name: order_payments
    - name: product_catagory_name_translation
    - name: products
    - name: sellers
    - name: items
    - name: orders